### ISSUE TITLE
Error while running "yo polymer-typescript"

### ISSUE THREAD

**Issue by denishamann** [taktik/generator-polymer-typescript#1]
Hello,

I got an error when executing ```yo polymer-typescript``` with npm version 5.5.1 and node v6.11.4
I upgraded my node to v8.9.1 and it worked fine.

Here is the error i got:
```
/usr/local/lib/node_modules/generator-polymer-typescript/generators/app/index.js:81
    );
    ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as polymer-typescript:app] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:38:27)
```

**Comment by hubjac1** [comment]
Hi @denishamann,
Interesting, this project is tested with travis on different node versions (v6.12.0, v7.10.1 and v8.9.1).
If this issue only append with node < v6.12.0 I don't think is a real problem. It's even not supported by node team either.

**Comment by hubjac1** [comment]
This issue occurs also with node v7.8.x.
It should be fix with the next release
